#!/bin/bash
[[ -z "$1" ]] &&  echo 'Usage: OPTS="" '$0' name-of-container [image-to-run]' && exit 255
docker=$(realpath `dirname $0`)
image=$([[ -z "$2" ]] && echo 'centos:7' || echo $2)
if [[ -f "$2" ]]; then
  $docker/utils/import ${2%%.*} $2
  image=$2
fi

test ! -d $docker/containers && mkdir $_
init=$docker"/containers/$1"
if [[ ! -f $init ]]; then
  cp -f $docker/init $init
fi

test ! -d /storage/$1 && mkdir $_
docker create --name "$1" --hostname "$1" --restart=always --cap-add=NET_ADMIN \
  -v $init:/init -v /storage/$1:/storage $OPTS -i -t $image /init
