#!/bin/bash
docker=$(realpath `dirname $0`)
running=$($docker/utils/running "$1");
if [[ "$running" == "true" ]]; then
  $docker/stop "$1"
fi

test -f $docker/containers/$1 && mv $_ $docker/trash/container-$1-`date +%Y%m%d%H%M`
docker rm "$1"
