#!/bin/bash
# Resize docker using devicemapper storage
[[ -z $1 || -z $2 ]] && echo 'Usage: '$0' [container-name] [size-in-gb]' && exit 255
docker=$(realpath `dirname $0`)
CID=$($docker/utils/id "$1")
DEV=$(basename $(echo /dev/mapper/docker-*-$CID))
dmsetup table $DEV | sed "s/0 [0-9]* thin/0 $(($2*1024*1024*1024/512)) thin/" | dmsetup load $DEV
dmsetup resume $DEV
resize2fs /dev/mapper/$DEV
docker start $CID
docker logs $CID
