#!/bin/bash
[[ -z "$1" ]] && echo 'Usage: '$0' name-of-container' && exit 255

docker=$(realpath `dirname $0`)

echo 'Stopping...'
$docker/stop "$1"
echo '...done'

echo 'Starting...'
$docker/start "$1"
echo '...done'


