#!/usr/bin/env bash
cmd="$1"
shift
args="$*"
BIN_PATH=$(cd `dirname $0` && pwd)/scripts

# todo: add --help argument to display more info on each command
case "$cmd" in
  create)
    exec $BIN_PATH/create $args
    ;;
  start)
    docker start $args
    ;;
  stop)
    docker stop $args
    ;;
  enter)
    exec $BIN_PATH/exec $args bash
    ;;
  remove)
    exec $BIN_PATH/remove $args
    ;;
  dockerfile)
    exec $BIN_PATH/lego create $args
    ;;
  build)
    exec $BIN_PATH/lego build $args
    ;;
  *)
    echo 'Usage: yoda [command] [arguments]'
    echo 'Available commands:'
    echo '  create – create container using image'
    echo '  enter – enter to running container using bash'
    echo '  remove – remove existing container with assigned name'
    echo '  start – start created container'
    echo '  stop – stop create container'
    echo '  dockerfile – build dockerfile using instructions in parts'
    echo '  build – build docker image with parts selected'
    echo 'Each command has own arguments list'
    ;;
esac
