#!/usr/bin/env bash
set -e

# Update common system
dnf install -y epel-release
dnf update -y

# Install usable cli tools
# libzip is for docker-compose
dnf group install -y "Development Tools"
dnf install -y chrony nano dstat htop curl libzip git git-secret

# Upgrade kernel to support overlayfs2
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
rpm -Uvh http://www.elrepo.org/elrepo-release-8.0-2.el8.elrepo.noarch.rpm
dnf --enablerepo=elrepo-kernel install -y kernel-ml
grub2-set-default 0

# Install docker
dnf install -y dnf-utils \
  device-mapper-persistent-data \
  lvm2
dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
dnf install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.4.3-3.1.el7.x86_64.rpm
dnf install -y docker-ce-20.10.2-3.el8

# Preparing docker to start
cp daemon.json /etc/docker/
systemctl daemon-reload
systemctl enable docker

# Install docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
chmod +x /usr/bin/docker-compose

# Bash completion for docker
dnf install -y bash-completion
curl -L https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash -o /etc/bash_completion.d/docker-machine
curl -L https://raw.githubusercontent.com/docker/compose/1.27.4/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

# Install firewalld
dnf install -y firewalld

# Open port
systemctl start firewalld
systemctl enable firewalld

systemctl enable chronyd
systemctl start chronyd

# Generate locale
# localedef -i en_US -f utf8 en_US.utf8

bash ./setup

shutdown -r now
