#!/usr/bin/env bash
# Setup users first
for user in admin box; do
  useradd $user
  mkdir /home/$user/.ssh && chown $user:$user "$_" && chmod 700 "$_"
  cp "$SERVER_ROOT/authorized_keys" /home/$user/.ssh/
  echo 'HISTTIMEFORMAT="%Y-%m-%d %T "' >> $user/.bashrc
  chown $user:$user /home/$user/{.ssh/authorized_keys,.bashrc} && chmod 600 "$_"
done

# Save time for history for root also
echo 'HISTTIMEFORMAT="%Y-%m-%d %T "' >> /root/.bashrc

# Add docker group to box user
usermod -aG docker box

# Setup sudo for admin
echo '%admin  ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Apply server wide configurations
cp -f "$SERVER_ROOT/sshd_config" /etc/ssh/sshd_config
systemctl reload sshd
cp -f "$SERVER_ROOT/sysctl.conf" /etc/sysctl.conf
sysctl -p
