#!/bin/bash
[[ -z $1 ]] && echo 'Usage: '$0' ip-range-with-cidr' && exit 255

# default for docker0 is 172.17.42.1/16
ip link add docker0 type bridge
ip addr add $1 dev docker0
ip link set docker0 up
