#!/usr/bin/env bash
export YODA_VERSION="{{yoda_version}}"

commit=$(git rev-parse HEAD 2>/dev/null || echo 'latest')
export REVISION=${REVISION:-$commit}
export REVISION_TAG
REVISION_TAG=$(git describe --exact-match "$commit" 2>/dev/null || true)

export GIT_URL
GIT_URL=$(git config --get remote.origin.url 2> /dev/null || true)

export GIT_BRANCH
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2> /dev/null || echo 'master')

export SOURCE_PATH
SOURCE_PATH=$(pwd)

export DOCKER_ROOT
DOCKER_ROOT=$(cd "${BASH_SOURCE%/*}" && pwd)

export HOSTNAME=${HOSTNAME:-$(hostname)}
export ENV=${ENV:-dev}

export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-"{{name}}"}
export COMPOSE_HTTP_TIMEOUT=${COMPOSE_HTTP_TIMEOUT:-300}
export MAIN_COMPOSE_FILE="$DOCKER_ROOT/docker-compose.yml"
export COMPOSE_FILE="$DOCKER_ROOT/docker-compose.$ENV.yml"

# Wait # seconds before kill -9 stopping container
export STOP_WAIT_TIMEOUT=${STOP_WAIT_TIMEOUT:-10}

# If 1 names will be project.container.0 also when scale not set
export CONTAINER_SCALE_INDEX=${CONTAINER_SCALE_INDEX:-1}

# If you use this be sure to run yoda build --push by self before deploying
export REGISTRY_URL=${REGISTRY_URL:-''}
