#!/usr/bin/env bash
for p in "$@"; do
  case $p in
    --image=*)
      image=${p#*=}
      ;;
    --ip=*)
      ip=${p#*=}
      ;;
    --expose=*)
      expose=${p#*=}
      ;;
    --options=*)
      options=${p#*=}
      ;;
    --args=*)
      cmd_args=${p#*=}
      ;;
    *)
      name=$p
      ;;
  esac
done

if [[ -z "$name" ]]; then
  echo 'Usage: '$0' [options] container-name'
  echo "Where [options] are:"
  echo "  --image"
  echo "    Docker image to use for creating current container. Default is yoda"
  echo "  --ip"
  echo "    IP address for container in subnet of docker network yodanet. Default is autoassigned by docker"
  echo "  --expose"
  echo "    Expose selected ports in container. Default is none"
  echo "  --options"
  echo "    Optional arguments as a string to pass for docker create command"
  echo "  --args"
  echo "    Entrypoint command arguments to init script"
  exit 1
fi
docker=$(cd `dirname $0`/.. && pwd)
source "$docker/config.sh"

# Try to create image if not exists
image_count=$(docker images --format '{{.ID}}' "${CONTAINER_IMAGE}:${CONTAINER_IMAGE_VERSION}")
if [[ -z "$image_count" ]]; then
  echo 'Creating base image for containers: '$CONTAINER_IMAGE
  docker build --rm=true -t ${CONTAINER_IMAGE}:${CONTAINER_IMAGE_VERSION} -t ${CONTAINER_IMAGE}:latest - < $0 dockerfile
  [[ "$?" != "0" ]] && echo 'Error while building main yoda image' && exit 1
fi

image=${image-$CONTAINER_IMAGE}
if [[ -f "$image" ]]; then
  $docker/utils/import ${image%%.*} $image
  [[ "$?" != "0" ]] && echo 'Error while importing image' && exit 1
fi

docker network inspect $CONTAINER_NETWORK_NAME 1>/dev/null 2>&1
if [[ "$?" != "0" ]]; then
  echo "Creating network interface $CONTAINER_NETWORK_NAME with subnet $CONTAINER_NETWORK_SUBNET"
  docker network create --subnet="$CONTAINER_NETWORK_SUBNET" $CONTAINER_NETWORK_NAME
  [[ "$?" != "0" ]] && echo 'Error while creating network' && exit 1
fi

test ! -d $docker/containers && mkdir $_
init=$docker"/containers/$name"
if [[ ! -f $init ]]; then
  cp -f $docker/init $init
fi

test ! -d $docker/storage/$name && mkdir -p $_

# Make extra opts for create command depends on parameters
arg_opts=''
if [[ -n "$ip" ]]; then
  arg_opts=arg_opts' --ip "'$ip'"'
fi

if [[ -n "$expose" ]]; then
  arg_opts=arg_opts' --expose "'$expose'"'
fi

docker create --name "$name" --net "$CONTAINER_NETWORK_NAME" $arg_opts --hostname "$name" --restart=always \
  -v $init:/init -v $docker/storage/$name:/storage $options -it $image $cmd_args
