#!/usr/bin/env bash
cmd="$1"
shift
PART_PATH=$(cd `dirname $0`/.. && pwd)/parts
LAYOUT_PATH=$(cd `dirname $0`/.. && pwd)/layout

for p in "$@"; do
  case "$p" in
    --parts=*)
      parts="${p##*=}"
      ;;
    *)
      name="$p"
      ;;
  esac
done

case "$cmd" in
  create)
    body="# Layout / Header"$'\n'
    body+=$(cat $LAYOUT_PATH/header)$'\n'$'\n'
    for part in $parts; do
      body+="# $part"$'\n'
      body+=$(cat $PART_PATH/$part)$'\n'$'\n'
    done
    body+="# Layout / Footer"$'\n'
    body+=$(cat $LAYOUT_PATH/footer)

    if [[ -n "$name" ]]; then
      if [[ -e $name ]]; then
        echo 'File '$name' already exists'
        exit 1
      else
        echo 'Save into a file: '$name
        echo "$body" > $name
      fi
    else
      echo "$body"
    fi
    ;;
  build)
    args=''
    if [[ -n "$name" ]]; then
      args+="-t $name"
    fi
    exec $0 create --parts="$parts" | docker build $args -
    ;;
  *)
    echo 'Usage: ./lego command --parts=[parts] [name]'
    echo 'Available commands: create, build'
    exit 1
esac
