#!/usr/bin/env bash
# Update common system
yum install -y epel-release
yum update -y

# Install usable cli tools
yum install -y nano dstat htop curl

# Upgrade kernel to support overlayfs2
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
yum --enablerepo=elrepo-kernel install -y kernel-ml
grub2-set-default 0

# Install git
git_version=2.12.0
yum install -y curl-devel expat-devel gettext-devel openssl-devel zlib-devel gcc perl-ExtUtils-MakeMaker
curl -sSL https://github.com/git/git/archive/v${git_version}.tar.gz | tar xzf -
cd git-${git_version}
make prefix=/usr all
make prefix=/usr install
cd .. && rm -fr git-${git_version}

# Install docker
yum install -y yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y docker-ce

# Preparing docker to start
sed -i 's|ExecStart=/usr/bin/dockerd|ExecStart=/usr/bin/dockerd --storage-driver=overlay2 --iptables=false --live-restore|' /usr/lib/systemd/system/docker.service
systemctl daemon-reload
systemctl enable docker
systemctl start docker

# Install docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Open port
firewall-cmd --zone=public --add-port=80/tcp --add-port=443/tcp --permanent
firewall-cmd --reload

# Generate locale
localedef -i en_US -f UTF-8 en_US.UTF-8

# Reboot now
shutdown -r now
